#CRAGS= -Wall -Werror -ansi -pedantic

main: main.o displayGrid.o displayCPU.o open.o

main.o: main.c struct.h
open.o: open.c
displayGrid.o: displayGrid.c struct.h
displayCPU.o: displayCPU.c struct.h
